name: daily-tracker
services:
  daily-tracker:
    image: ghcr.io/jrhattigan1/daily-tracker:latest
    container_name: daily-tracker
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - /DATA/AppData/daily-tracker/data:/data
    environment:
      - TZ=Europe/London
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: daily-tracker-updater
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/London
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
